### ISSUE TITLE
Can OSOAA be used to simulate the single scattering of radiation transmission by setting SOS.IGMAX = 1 ?

### ISSUE THREAD

**Issue by Tianfeng-Pink** [CNES/RadiativeTransferCode-OSOAA#10]
Can OSOAA be used to simulate the single scattering of radiation transmission by setting SOS.IGMAX = 1 ? Multiple scattering is not considered.

**Comment by blafranc** [comment]
By setting SOS.IGMAX=1, you will simulate :
1.	The reflection on the seabed of the direct solar beam transmitted from Top Of the Atmosphere to the seabed.
2.	The single scattering both in the sea and the atmosphere.
3.	The sea-to-air transmission of the single scattering radiance in the water.
4.	The direct solar reflection on the sea surface (sun-glint and foam reflections).
 
Hoping this answer will help you.

**Comment by Tianfeng-Pink** [comment]
> By setting SOS.IGMAX=1, you will simulate :
> 
> 1. The reflection on the seabed of the direct solar beam transmitted from Top Of the Atmosphere to the seabed.
> 2. The single scattering both in the sea and the atmosphere.
> 3. The sea-to-air transmission of the single scattering radiance in the water.
> 4. The direct solar reflection on the sea surface (sun-glint and foam reflections).
> 
> Hoping this answer will help you.

Thanks very much for your reply, which is very helpful to me.
