### ISSUE TITLE
Gauss angles

### ISSUE THREAD

**Issue by lucasbarbedo83** [CNES/RadiativeTransferCode-OSOAA#14]
I have a question about the term gauss angles.
What is the difference between gauss-angles and angles? 

For example:
 ****************************
 OSOAA_HYDROSOLS :  
 ****************************
 
 Wavelength for radiance simulation:  0.59999999999999998     
 
 USED ANGLES
 ***********
  
 Total number of angles :           41
 Number of Gauss angles :           40

**Comment by blafranc** [comment]
The Gauss angles are used to perform the spatial integrations of the radiance fields.

The radiance can be calculated for other angles provided by the user. The radiance is then properly calculated for these angles (i.e. it is not interpolated from Gauss angles). These user's angles are not used to calculate the spatial integrations.

The solar zenith angle is also added in the list of angles.
