### ISSUE TITLE
Sun Glint and White Foam

### ISSUE THREAD

**Issue by amsuhail** [CNES/RadiativeTransferCode-OSOAA#18]
Hi,

Does OSOAA account for the effects of sun glint and white foam in the radiative transfer or it ignores them?

Regards,
Suhail

**Comment by blafranc** [comment]
Hello,

Yes, the **OSOAA model simulates the sun glin**t. You can define the wind speed with the parameter -SEA.Wind and sea/surface refraction index with -SEA.Ind.
The **foam can be introduced** by defining its reflectance contribution with the parameter -SEA.SurfAlb.

Please, have a look in the **User Guide**:
- Foam is mentioned in section §3.2.2, page 23.
- The sea surface modeling is fully described in section §4.4, page 100 onwards.

Best regards
