### ISSUE TITLE
The Junge's law model in OSOAA

### ISSUE THREAD

**Issue by yichen-li2016** [CNES/RadiativeTransferCode-OSOAA#19]
Hi,

Recently, while using OSOAA, I'm confused in two ways. First, I found that the Junge model in the Hydrosol models is N(D)=r**-v, and in the open ocean, when v=4, I get the following particle size distribution. This result differs by many orders of magnitude from that in Stramski et al. 2001. So I would like to ask if there exists a coefficient K for the Junge distribution N(r) = Kr**-v here, or is the unit of N(r) used by default in OSOAA [um**-4]?
![PSD](https://github.com/CNES/RadiativeTransferCode-OSOAA/assets/76198652/1a2bb0c0-8fee-45ca-8966-7278220debfa)
![image](https://github.com/CNES/RadiativeTransferCode-OSOAA/assets/76198652/f4d13820-d237-4f7b-beec-724979a2dd19)

Second, I see from the ANGLES.Log file that the number of Gauss angles used for phase function calculations is 40, distributed over [0, pi/2]. However, the number of angles in the HYD_MIE.Log file that I got is 83, distributed over [0, pi]. I would like to know how this is done in the actual calculation? Also, if I choose HYD.Model=2 and I set the same number of angles and distribution as in ANGLES.Log, can I get the same result as HYD_MIE.Log?

Best regards,
Qiang

**Comment by blafranc** [comment]
Hello,

**Response to question 1 : "Junge model"**
The size distribution is used to calculate the scattering and extinction cross-sections equivalent to an average particle size. The number of particles is not necessary to get these radiative terms. That is why the Junge distribution is expressed by N(r) = r**-v and not by Kr**-v. 

**Response to question 2 : "Gauss angles"**
N Gauss angles are calculated over [0, pi/2].
The opposite value of each Gauss angle is added to discribe the phase functions  over [0, pi], giving to 2N angles.
The angles 0°, 90° and 180° complete the list of angles for the log file, giving to 2N+3 angles.

Hoping these answers help.
Best regards

**Comment by yichen-li2016** [comment]
Hi,

Thank you, your reply has been of great help to me!

Best regards,
Qiang
