### ISSUE TITLE
Can not compile.

### ISSUE THREAD

**Issue by ghost** [CNES/RadiativeTransferCode-OSOAA#3]
Environment: Ubuntu
ERROR: `Makefile_OSOAA.gfortran:90: *** target pattern contains no '%'.  Stop.`
The error is as follows:
![Screenshot from 2019-06-10 09-33-05](https://user-images.githubusercontent.com/15885479/59167244-d8b04f80-8b62-11e9-9d8d-0184535541cf.png)
How to solve the problem?

**Comment by ghost** [comment]
Solved.
I rename file `Makefile_OSOAA.f77` to `Makefile_OSOAA.makefile`
then, run command `make -f Makefile_OSOAA.makefile`
it works.
![Screenshot from 2019-06-10 14-46-45](https://user-images.githubusercontent.com/15885479/59177413-9ef53e00-8b8e-11e9-9c81-d27985a64591.png)

**Comment by SOEDLI** [comment]
<img width="916" alt="Snipaste_2024-11-23_16-54-57" src="https://github.com/user-attachments/assets/bf1ca0ae-56f2-4687-9fb4-9b9e4ca53151">
Environment: Ubuntu18.04
ERROR: make: gfortran : Command not found
Why does this problem occur?
