### ISSUE TITLE
small bug detected in scattering matrix computation

### ISSUE THREAD

**Issue by Tristanovsk** [CNES/RadiativeTransferCode-OSOAA#4]
I just noticed that XMU(0) is not initialized to zero in OSOAA_HYDROSOLS.F and OSOAA_AROSOLS.F. This can yield erroneous values for the scattering matrices at 90° scattering angle (it was the case for me for hydrosols).
fix: 
add
```
! initialize XMU for index 0
      XMU(0)=0.
```
in OSOAA_AROSOLS.F at row 786
in OSOAA_HYDROSOLS.F at row 625

**Comment by CDesj** [comment]
Thank you for your comment. Our verification shows that there is no bug in the model. It seems that the specific configuration of your run  is not supposed to be taken into account by the model. We invite you to contact directly the PI-scientists of the OSOAA model if you need more explanations
