### ISSUE TITLE
OSOAA simulates the effect of relative azimuth on TOA reflectance

### ISSUE THREAD

**Issue by ghost** [CNES/RadiativeTransferCode-OSOAA#5]
[issue-495165915](https://github.com/fnemina/AtmosphericCorrection/issues/12#issue-495165915)

**Comment by blafranc** [comment]
Hello,

Thank you for your interest in using the OSOAA radiative transfer model.

For your simulations, you defined a wind speed equals to 10m/s.
That means the glitter pattern is strongly spread around the specular direction, which corresponds to the direction phi=0 and VZA=SZA=45°, according to your simulation parameters.

Let's note the relative azimuth angle convention for the OSOAA code is, in solar principal plane :
- for the specular half-plane, phi = 0°
- for the backscattering half-plane, phi = 180°._

With a large glitter pattern, reducing the relative azimuth angle phi induces an increasing impact of  the sunglint on the measurement (or simulation).
When you consider back-scattering directions (phi > 90°), you observe variations of the atmospheric scattering with the azimuth angle.
This is consistent with observations on your plots.

For a better understanding of the physics acting on the simulations, we suggest you to have a look on the paper of Pr. Chami ( https://www.mdpi.com/2072-4292/12/9/1445).
Figure 1a shows the  glitter pattern around the specular direction  (in this illustration the wind speed equals to 5m/s, so the spreading of the glitter pattern is lower than with 10m/s)
Figure 1b shows the impact on the TOA signal of the atmospheric scattering for backscattering directions.
Figure 2b shows the impact of the sunglint pattern as a function of the relative azimuth (let's see the blue and turquoise circles around phi=0°).

Moreover, the spectral dependence is consistent too with the physics of the simulated scene.
Indeed: i) the sunglint contribution on the signal is the highest for the specular half-plane (phi = 0), and ii), as you know, the sunglint is not dependent on the wavelength (according to a neglecting change of the sea water refractive index on the considered spectral range 400 - 800 nm).
Therefore, the sunglint contribution is the same from 400 to 800 nm, while the atmospheric scattering decreases and the atmospheric transmittance increases (neglecting the gaseous absorption).
As, the sunglint is the main contributor to the observed signal, it is consistent to notice a low spectral variation of the simulation from 400 to 800nm, in the  specular half-plane (phi = 0).
The balance between atmospheric scattering and attenuation of the sunglint reflection explains why it is not exactly the same signal over wavelengths.

At the opposite, far from the sunglint pattern, i.e. with a large value of phi, you only observe the spectral variation of the atmospheric scattering.

We hope these clarifications will help you in your study project.

Best regards
Dr Bruno Lafrance
