### ISSUE TITLE
Can this code be used generating Rayleigh and aerosol look-up table (seadas) ？

### ISSUE THREAD

**Issue by lwk1542** [CNES/RadiativeTransferCode-OSOAA#9]

**Comment by ghost** [comment]
@fnemina generated [SeaWiFS Rayleigh and Aerosol LUT](https://github.com/fnemina/seawifs-osoaa) using OSOAA

**Comment by fnemina** [comment]
As QiaoFeng says I've donde so in the past. If you need help with this please write me and I will try to provide this.

**Comment by blafranc** [comment]
Thank you for your question. 
I confirm you that it is possible to generate LUT for various atmosphere and/or ocean optical properties. 
The current version of OSOAA provides the various programs for performing one single run. 
However, you can simulate any LUT by  adapting  the shell script that allows performing OSOAA runs in command line (see the demonstration script in ksh or csh provided in the directory "exe/") using loops on any variable of interests for your study. As an example, to simulate Rayleigh and Aerosol LUT, your loops may concern the Rayleigh variables (optical depth, wavelength) and the aerosols variables (optical depth, aerosol model parameters, etc.). If you do not wish to use the demonstration shell script provided in exe/ directory, you can alternatively  write your own script in any other language (e.g., python) to perform loops on any of the OSOAA input parameters of interest for your study.

**Comment by humbm** [comment]
> As QiaoFeng says I've donde so in the past. If you need help with this please write me and I will try to provide this.

Recently I would like generate SeaWiFS Rayleigh LUT using OSOAA. Could you provide me some tips so I could make it?
